### ISSUE TITLE
[Next.js] HMR / Auto-reload

### ISSUE THREAD

**Issue by brillout** [vikejs/telefunc#10]
As shown in `/examples/next` Telefunc supports Next.js.

But I believe creating a new `.telefunc.js` file requires the user to stop and restart the Next.js dev server, @Aslemammad can you confirm this?

I've an idea how to solve this.

**Comment by Aslemammad** [comment]
Please mention your idea, so I can work on this!

**Comment by brillout** [comment]
Thanks @Aslemammad I appreciate your help.

2 ideas:
 - We re-run fast-glob on each `_telefunc` HTTP request. (My favoriate so far: it's simpler and since we already use fast-glob we don't bloat the Next.js integration with an additional dependency.)
 - We use [chokidar](https://github.com/paulmillr/chokidar).

This should solve the need for restarting the Next.js dev server.

**Comment by brillout** [comment]
Done.
