### ISSUE TITLE
Should telefunc work with Vercel & other serverless platforms?

### ISSUE THREAD

**Issue by mdixon4** [vikejs/telefunc#17]
Hi Rom, I'm struggling to get telefunc to work with vite-plugin-ssr and vercel.

* Example repo: https://github.com/mdixon4/vite-plugin-ssr-vercel-telefunc
* Deployed to: https://vite-plugin-ssr-vercel-telefunc.vercel.app/

I started from the example at https://github.com/brillout/vite-plugin-ssr/tree/master/examples/vercel and I added telefunc as illustrated in https://github.com/vikejs/telefunc/tree/master/examples/vite-plugin-ssr. I added a button on the home page which is meant to call a telefunc function - and this works in the dev express server.

To make it work in Vercel I added a check to the vercel handler: `if (url.startsWith('/_telefunc')) {}` and called the telefunc handler in there. I also imported `../dist/server/importTelefuncFiles.js` in `vercel/render.js` a la the similar import `../dist/server/importBuild.js` but really not sure whether I should've or not.

Regardless, something does not quite work with the deploy step - see the following function log:

```
Request to url: /_telefunc
2022-02-11T12:01:53.645Z	47057682-17e9-45ed-a95b-574f2f269df7	ERROR	Error: [telefunc@0.1.10][Wrong Usage] Make sure to run `vite build && vite build --ssr` before running your Node.js server with `createTelefuncCaller({ isProduction: true })`. (Build file /var/task/dist/server/importTelefuncFiles.js is missing.)
    at loadViteEntry (/var/task/index.js:62944:33)
    at loadTelefuncFilesWithVite (/var/task/index.js:62906:67)
    at loadTelefuncFiles (/var/task/index.js:61781:74)
    at runTelefunc_ (/var/task/index.js:61431:108)
    at runTelefunc (/var/task/index.js:61403:22)
    at telefunc (/var/task/index.js:62341:62)
    at Server.handler (/var/task/index.js:68307:32)
```

Should this work? Do you have any advice about how to proceed?

Thanks!

**Comment by brillout** [comment]
Yes, it should work. A user is actually doing what you want (Telefunc + vite-pugin-ssr + Vercel).

Let me have a look.

**Comment by brillout** [comment]
@magne4000 is your Telefunc + vite-plugin-ssr + Vercel app public?

**Comment by mdixon4** [comment]
Correct - the error stack comes from the Vercel production logs.

**Comment by brillout** [comment]
@mdixon4 If it's ok for you, let's wait for @magne4000's answer and then continue digging.

Vercel will work as, from Vercel's perspective, Telefunc has the exact same architecture than vite-plugin-ssr, and vite-plugin-ssr does support Vercel. It's probably just a little misconfiguration.

**Comment by magne4000** [comment]
Only thing I did different, is that I'm importing `importBuild.js` instead of directly `importTelefuncFiles.js`. but I guess that just the following snippet from `importBuild.js` should be necessary:
![image](https://user-images.githubusercontent.com/1098371/153669066-a89baa18-941b-49a8-aacf-56c96e0af38f.png)

From your error message, I'm guessing you are missing the last two lines.Add them or directly imported `importBuild.js` instead and check if this works. If it's still not working, I'll share a more complete version of what I did.

**Comment by brillout** [comment]
He actually does use `importBuild.js`: https://github.com/mdixon4/vite-plugin-ssr-vercel-telefunc/blob/e70dae9250a7fbd6ebd63ea2c79efb50cfe20fc7/vercel/render.js#L4.

**Comment by magne4000** [comment]
Indeed, so importing the second one should not be necessary :shrug: . I suppose that somewhere in the process Vercel cleans it up because it's unused

**Comment by brillout** [comment]
@magne4000 👍 

@mdixon4 Also, try to remove Telefunc altogether and see if it works. I suspect that it still won't. And check your Vercel config in Vercel's web UI to match what is described here https://vite-plugin-ssr.com/vercel.

**Comment by magne4000** [comment]
It's worth noting that I'm still using the "old" vite-plugin-ssr Vercel config myself which does not leverage the `.output` directory

**Comment by brillout** [comment]
I will have a look tonight / tomorrow.

**Comment by brillout** [comment]
I also made it work with the old technique https://telefunc-vercel-ssr-old-technique.vercel.app/.

But indeed there seem to be a problem with the new technique. I'll continue digging.

**Comment by mdixon4** [comment]
Thanks for investigating @brillout. That old technique makes sense, and since it works, that might be the trick. Seems the main difference is the code isn't bundled for Vercel? Is there any real downside to this? What is suboptimal with this technique that the new technique is trying to fix?

**Comment by brillout** [comment]
Alright, this works: https://github.com/brillout/telefunc-vercel-ssr.

It uses the "old" technique which is not outdated at all; it's just what vps officially recommended a while ago.

Using Vercel's Filesystem API (the "new" technique) will also work with Telefunc. (I've found why it currently fails and I'll implement the fix this week.)

After further digging, I think the `api/` way (the "old" technique) makes more sense also for vps, so I will actuallly change the official vps recommendation back to the "old" technique.

I'm leaving this ticket open for tracking Filesystem API support and adding documentation to telefunc.com.

**Comment by mdixon4** [comment]
Thanks for all your investigation! That old technique is working for me too. Thanks again.

**Comment by brillout** [comment]
Vercel now works out-of-the-box, with both techniques. And no need to import `importBuild.js` anymore (for Telefunc; you still need to do this for vite-plugin-ssr).

Examples: https://github.com/vikejs/telefunc/tree/master/examples/vercel.
