### ISSUE TITLE
Patterns to test Telefunc 

### ISSUE THREAD

**Issue by Sajad-Sharhani** [vikejs/telefunc#19]
Is there a way of testing Telefunc without the UI components?

**Comment by brillout** [comment]
Not sure what you mean; what is it you are trying to achieve?

**Comment by Sajad-Sharhani** [comment]
For example, when the frontend and backend are separated, we test the API with the postman or graphql playground.
Is there a way to use prev backend pattern to test `.telefunc` functions without importing them into pages?

**Comment by brillout** [comment]
Yes, simply recreate an HTTP request made by the Telefunc client. You can then, for example, use `curl`.

(I'm closing this ticket beause it's something Telefunc end-users wouldn't need: I'm assuming you need this because you want to experiment with RSC.)

Let me know if you have further questions.
