### ISSUE TITLE
New Hook `getPermission()`

### ISSUE THREAD

**Issue by brillout** [vikejs/telefunc#27]
As discussed in #12 we want to offer an option to harden the security of telefunctions. CC @redbar0n.

```ts
// server.js
// Enviroment: Node.js

import { telefuncConfig } from 'telefunc'
telefuncConfig.enforcePermissions = true
```

When `enforcePermissions` is set to `true`, all telefunctions need to use a hook called `getPermission()`.

```ts
// *.telefunc.ts
// Enviroment: Node.js

import { getPermission } from 'telefunc'
import { allowEveryone, allowAuthor, allowAdmin } from './permissions'

export function hello() {
  getPermission(allowEveryone)
  // ...
}

export function updateTodo(id: string) {
  getPermission(() => allowAuthor(id))
  // ...
}

export function deleteUser(id: string) {
  getPermission(() => allowAdmin())
  // ...
}
```

```ts
// permissions.ts
// Enviroment: Node.js

// Permissions defined by the user.

export function allowEveryone() {
  // ...
}
export function allowAuthor(rowId: string) {
  // ...
}
export function allowAdmin() {
  // ...
}
```

@louwers thoughts?

**Comment by louwers** [comment]
@brillout How would this work with passing information to the frontend?

How could you add tests for the permissions of your Telefunctions?

So the way it would work is: reset some variable, run the Telefunction, and not return the result if `getPermission` was not called, or if `false` was passed to it, correct? If so it would still have side-effects if `getPermission`was called in the wrong place or not called at all? (Just add a note to the docs to call `getPermission` first I guess).

Random thought: but is it possible to do this with static analysis (ESLint rule?) instead of a hook? And then allow the user to define how permissions should be handled, but we give write an opinionated ESLint rule. I personally like the idea of Telefunction files to be just Typescript files without any 'framework code', but that might be irrational.

In general, I like how simple it is. I'd like a bit more configuration or flexibility, for example, make all Telefunctions public in `*.public.telefunc.(ts|js)`?

```ts
telefuncConfig.enforcePermissions = {
  match: /*.public.telefunc.(ts|js)/
}
```

**Comment by brillout** [comment]
The original design I had in mind was this:

```ts
// Comment.telefunc.ts

import { allow, getContext } from 'telefunc'

allow(deleteComment, () => {
  const { user } = getContext()
  return user.isAdmin
})
export async function deleteComment(id: string) {
  //...
}
```

But this is problematic for following use case:

```ts
// TodoItem.telefunc.ts

import { allow, getContext } from 'telefunc'

allow(onTodoTextChange, async (id: string) => {
  const { user } = getContext()
  const todoItem = await Todo.findOne({ id })
  return todoItem.authorId === user.id
})
export async function onTodoTextChange (id: string, text: string) {
  const { user } = getContext()
  // That's bad: we are fetching `todoItem` twice from the database
  const todoItem = await Todo.findOne({ id })
  todoItem.text = text
  await todoItem._save()
}
```

If we add an extra parameter `onTodoTextChange(id, text, providedByAllow)` then TypeScript will complain that `providedByAllow` is missing when the client-side calls `onTodoTextChange()`.

That's why I ended up with the `getPermission()` design.

```ts
// todoItem.telefunc.ts

import { getPermission, getContext } from 'telefunc'

// Note how we fetch `todoItem` from the database only once
async function allowAuthor(id) {
  const { user } = getContext()
  const todoItem = await Todo.findOne({ id })
  const givePermission = todoItem.authorId === user.id
  return { givePermission, returnValue: todoItem }
}
export async function onTodoTextChange (id: string, text: string) {
  const todoItem = await getPermission(() => allowAuthor(id))
  todoItem.text = text
  await todoItem._save()
}
```

> if `getPermission` was called in the wrong place or not called at all

I think it's unlikely to happen. Let me elaborate.

First, like `getContext()`, `getPermission()` only works before any async operation:

```js
async function onTodoTextChange() {
  const todoItem = await Todo.findOne({ id })
  // Doesn't work and Telefunc throws an error
  getPermission(/* ... */)
}
```

This strongly limits potential for side-effects.

Now it's true that, if the user forgets `getPermission()`, then Telefunc cannot abort the side-effects. But Telefunc shows a warning in the console saying that `getPermission()` is missing. We can assume the user to see the warning and correct his telefunction.

Note that detecting the presence of `getPermission()` is deterministic because using `getPermission()` inside an if-branch is an anti-pattern.

```ts
async function someTelefunction() {
  // This is an anti-pattern.
  // Maybe an ESLint rule could ensure that the user doens't do that.
  if (someCondition) {
    getPermission(/* ... */)
  }

  // Good:
  getPermission(() => {
    if (someCondition) {
      // ...
    }
  })
}
```

In other words, if a telefunction is missing `getPermission()`, then Telefunc systematically shows the warning.

> How could you add tests for the permissions of your Telefunctions?

A permission function is just a function, so I don't foresee problems with the user being able to unit test his permission functions.

> How would this work with passing information to the frontend?

A permission function can also throw a `throw Abort({ some: 'info' })` (which the frontend can access).

> static analysis

AFAICT, beyond ensuring that the user did not forget `getPermission()` (or some other function), I don't see how static analyis would help.

> instead of a hook? And then allow the user to define how permissions should be handled, but we give write an opinionated ESLint rule.

I think we do need some kind of hook.

For example, for the following, I don't see how static analysis can help.

```ts
export async function deleteComment(id: string) {
  const { user } = getContext()
  /* What should static analysis do if the following is missing?
  if (!user.isAdmin) {
    throw Abort()
  } */
  const comment = await Comment.findOne({ id })
  await comment._delete()
}
```

> I personally like the idea of Telefunction files to be just Typescript files without any 'framework code', but that might be irrational.

I share that sentiment and this is Telefunc's goal. I'd be up for a leaner solution.

> In general, I like how simple it is. I'd like a bit more configuration or flexibility, for example, make all Telefunctions public in `*.public.telefunc.(ts|js)`?

Clever idea, I like it. One problem though is that it multiplies the number of files:

```bash
TodoItem.tsx # React component
TodoItem.author.telefunc.tsx
TodoItem.public.telefunc.tsx
TodoItem.admin.telefunc.tsx
```

**Comment by bartenra** [comment]
```ts
  const todoItem = await getPermission(() => allowAuthor(id))
```

Hmm, don't like that a function called `getPermission` returns a todo. :see_no_evil:  I understand why this API would make sense, but I woudn't like to use it like that.

```ts
throw Abort({ some: 'info' })
```

This is not type safe, so I personally wouldn't like to use that either. What I mean is, how can I return a plain value (instead of throw an exception)?

> I share that sentiment and this is Telefunc's goal. I'd be up for a leaner solution.

Here is how I imagine static analysis to work:

We could check all `return` statements in a telefunction. At least one of them must be `PermissionDenied`. We can add this value to Telefunc or let the user define it.

```ts
const PermissionDenied = 'PERMISSION_DENIED';

export async function deleteComment(id: string) {
  const { user } = getContext()
  if (!user.isAdmin) {
    return PermissionDenied
  }
  const comment = await Comment.findOne({ id })
  await comment._delete()
}
```


OR one of the call expressions must return `never`.


```ts
function permissionDenied(): never {
  throw Abort()
}

export async function deleteComment(id: string) {
  const { user } = getContext()
  if (!user.isAdmin) {
    permissionDenied()
  }
  const comment = await Comment.findOne({ id })
  await comment._delete()
}
```

**Comment by brillout** [comment]
> Hmm, don't like that a function called getPermission returns a todo.

It seems weird at first, but I think it does make sense. Not only practically, but also semantically: the permission function validates the object and returns it. One way to think of it is that whatever is returned by `getPermission()` is safe.

> This is not type safe

Yes and the official recommendation is to `return someValue` instead, see https://telefunc.com/permissions. But there are some uses cases where `throw Abort('someValue')` is convenient and justifies its existence (e.g. to globally define authorization).

Note that `throw Abort()` (without arguments) is semantically correct though.

> We could check all return statements in a telefunction. At least one of them must be PermissionDenied. We can add this value to Telefunc or let the user define it.

That's an interesting idea and I do like it. Problem though: it's not trivial to get all return statements for all stacks (Vite, Parcel, Webpack, ...).

> OR one of the call expressions must return never.

Neat idea. I like it. Also because our shieldGenrator already provides us with a TS AST. I wonder if TypeScript provides us with that information though:

```ts
// Can TS differentiate them?

async function telefunction1(): Promise<string> {
  return 'hello'
}

async function telefunction2(): Promise<string> {
  if (someCondition) {
    throw Abort()
  }
  return 'hello'
}
```

> I'm not sure if I think a permission enforcement system even makes sense. Telefunctions are by default safe... If you don't put any code in them. 😂

Maybe you're right, seeing all the problems it causes, I'm thinking it may not be worth it.

How about we deprioritize this? We'll see if users will push more on this :-).

I still think enforcing permission functions to be a neat feature, but I'm coming to the conclusion there is no easy way to do a `enforePermission` thing.

We can leave it to the `getContext()` wrapper trick for the time being https://telefunc.com/permissions#getcontext-wrappers.

**Comment by bartenra** [comment]
> How about we deprioritize this? We'll see if users will push more on this :-).
> I still think enforcing permission functions to be a neat feature, but I'm coming to the conclusion there is no easy way to do a enforePermission thing.

:+1: 

> We can leave it to the getContext() wrapper trick for the time being https://telefunc.com/permissions#getcontext-wrappers.

I love that approach!

**Comment by brillout** [comment]
👍 Closing this in the meantime. Thanks for the neat discussion :-).
