### ISSUE TITLE
RFC: Generators api using streams

### ISSUE THREAD

**Issue by Aslemammad** [vikejs/telefunc#29]
Inspiration: [Tweet](https://twitter.com/anothergalvez/status/1523308987973779456) by @galvez

# Generators
As mentioned, generators can be easily integrated with Streams so it makes it easy to implement!
The idea is to give the ability to users to create generators in the server (like they do with telefunctions) so they have `Generator` in the client!
```js
// heavy result searching function
export function* onGetResult() {
  // db query for part 1 of the result
  const users = db({ ... })
  yield users;
  const groups = db({ ... })
  yield groups;
  const places = db({ ... })
  yield places;
}
```
client:
```js
const result = onGetResult()
result.next().value // users
result.next().value // groups
result.next().value // places
```

Feel free to discuss the limitations and the implementations!

Note: I believe it may be possible to also extend this api to Socket.

**Comment by brillout** [comment]
I did consider using generators for real-time use cases but, after much experimenting, I've came to the conclusion that functions are the wrong abstraction.

See conversation at https://discord.com/channels/815937377888632913/873214311957401631/985104860552790047.
