### ISSUE TITLE
[Wrong Usage] Using `shield()` (`import { shield } from 'telefunc'`) is forbidden on the client-side

### ISSUE THREAD

**Issue by oleghalin** [vikejs/telefunc#32]
Using Telefunc with Cloudflare Workers and vite-ssr-plugin. 

When running it on express dev server telefunc code executes only on backend side, while when i do wrangler dev i see this errors in console.

**Comment by brillout** [comment]
Since [/examples/cloudflare-workers](https://github.com/vikejs/telefunc/tree/master/examples/cloudflare-workers) is working, I suspect it's something due to your app?

**Comment by oleghalin** [comment]
i think so, but i assume that something related to combination of vsp and telefunc package, so i assumed that maybe you have some thoughts about it. So i no idea why worker tries to execute server code in browser. Anyway i got this error in Worker console, so it means that it was throw from server app. So i can assume that maybe some sort of condition which checks that its browser or server doesnt work properly on CF workers

**Comment by brillout** [comment]
I don't see how it could be related to vps. I'd dig into the worker code and see who's importing `shield`.

Unrelated: are you using wrangler 2? I'm asking because I couldn't find a way to inspect the worker code (but I didn't research long).

**Comment by oleghalin** [comment]
Im using wrangler2, currently trying to run your example with wrangler2

**Comment by oleghalin** [comment]
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/9086983/181765936-2d3af01b-b039-4afa-bcb8-9213ca979f74.png">
Doesnt work with wrangler2

**Comment by brillout** [comment]
I'll have a look.

Do you know where the worker code lives when using wrangler 2? I need to be able to inspect it.

**Comment by oleghalin** [comment]
Sorry, dont get your message correctly. It uploads it to Cloudflare edge workers, so you can inspect in their UI

**Comment by brillout** [comment]
👍 I'll try this.

(Although it would be more convenient to inspect it locally on my machine, just like I could with wrangler 1.)

**Comment by oleghalin** [comment]
You can use your example and just bump up wrangler version in packages.json.

Delete @cloudflare/wrangler and replace it with `"wrangler": "^2.0.21"` in sample packages.json

**Comment by brillout** [comment]
FYI https://github.com/cloudflare/wrangler2/issues/1580.

**Comment by brillout** [comment]
I'll have a look at this tomorrow.

**Comment by brillout** [comment]
Still having issues debugging worker code (https://github.com/cloudflare/wrangler2/issues/1580#issuecomment-1200299351). I'll take another stab at it tomorrow.

**Comment by brillout** [comment]
Fix released in `0.1.23`.
