### ISSUE TITLE
[Question] Is there way to try..catch error in browser?

### ISSUE THREAD

**Issue by oleghalin** [vikejs/telefunc#34]
Is there way to handle Abort in browser with try..catch block?

**Comment by brillout** [comment]
Why do you want to do this?

**Comment by oleghalin** [comment]
To handle errors on frontend, nvm i found solution. Is there way to throw Abort with custom status atleast not with 403?

**Comment by brillout** [comment]
>  Is there way to throw Abort with custom status atleast not with 403?

Why do you want to do this? The idea of Telefunc is you shouldn't care about these kinds of things. (But the docs may be lacking to properly explain common use cases.)

**Comment by oleghalin** [comment]
Currently, telefunc throws 403 and 500 errors, idea is to send 400 and 500 for different logic errors instead of sending the exact 403 code and 500 for internal issues. For example for access denied I wanna call abort with 403, for validation abort with logic code, and for fatal i will leave it for telefunc handler and i expect it will throw 500 .

**Comment by brillout** [comment]
Added docs about error handling: https://telefunc.com/error-handling.

Let me know if you have questions!
